"""initial_schema

Revision ID: 77722b349d7b
Revises: 
Create Date: 2026-06-20 14:58:10.429418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '77722b349d7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tracking_type', sa.Enum('pool', 'instance', name='asset_tracking_type', native_enum=False), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('three_d_item_key', sa.String(length=100), nullable=True),
    sa.Column('qr_prefix', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', 'client', name='user_role', native_enum=False), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.SmallInteger(), nullable=False),
    sa.Column('capacity_min', sa.Integer(), nullable=False),
    sa.Column('capacity_max', sa.Integer(), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'unavailable', name='venue_status', native_enum=False), nullable=False),
    sa.Column('three_d_room_id', sa.String(length=100), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('base_price_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('three_d_room_id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_entity_id'), 'activity_log', ['entity_id'], unique=False)
    op.create_table('asset_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('qr_code', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('available', 'reserved', 'in_use', 'maintenance', 'missing', name='asset_status', native_enum=False), nullable=False),
    sa.Column('current_venue_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index(op.f('ix_asset_instances_asset_id'), 'asset_instances', ['asset_id'], unique=False)
    op.create_table('event_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('attendee_count', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'under_review', 'quotation_sent', 'approved', 'confirmed', 'rejected', 'cancelled', 'completed', name='request_status', native_enum=False), nullable=False),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('setup_time_minutes', sa.Integer(), nullable=False),
    sa.Column('teardown_time_minutes', sa.Integer(), nullable=False),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('ai_proposal_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_requests_client_id'), 'event_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_event_requests_requested_date'), 'event_requests', ['requested_date'], unique=False)
    op.create_index(op.f('ix_event_requests_venue_id'), 'event_requests', ['venue_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_request_id', sa.Uuid(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_request_id'], ['event_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_request_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_confirmed', sa.Integer(), nullable=False),
    sa.Column('reservation_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reservation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'released', name='reservation_status', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reservation_end > reservation_start', name='chk_reservation_dates'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_request_id'], ['event_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_reservations_asset_id'), 'asset_reservations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_reservations_event_request_id'), 'asset_reservations', ['event_request_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_request_id', sa.Uuid(), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', name='quotation_status', native_enum=False), nullable=False),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_request_id'], ['event_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_event_request_id'), 'quotations', ['event_request_id'], unique=False)
    op.create_table('room_layouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('event_request_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'template', 'ai_generated', name='layout_source', native_enum=False), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_request_id'], ['event_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_layouts_is_current'), 'room_layouts', ['is_current'], unique=False)
    op.create_index(op.f('ix_room_layouts_venue_id'), 'room_layouts', ['venue_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_request_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('setup', 'teardown', 'preparation', 'logistics', 'coordination', name='task_type', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_progress', 'done', 'blocked', name='task_status', native_enum=False), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('depends_on', sa.Uuid(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['depends_on'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_request_id'], ['event_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_event_request_id'), 'tasks', ['event_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_event_request_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_room_layouts_venue_id'), table_name='room_layouts')
    op.drop_index(op.f('ix_room_layouts_is_current'), table_name='room_layouts')
    op.drop_table('room_layouts')
    op.drop_index(op.f('ix_quotations_event_request_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_asset_reservations_event_request_id'), table_name='asset_reservations')
    op.drop_index(op.f('ix_asset_reservations_asset_id'), table_name='asset_reservations')
    op.drop_table('asset_reservations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_event_requests_venue_id'), table_name='event_requests')
    op.drop_index(op.f('ix_event_requests_requested_date'), table_name='event_requests')
    op.drop_index(op.f('ix_event_requests_client_id'), table_name='event_requests')
    op.drop_table('event_requests')
    op.drop_index(op.f('ix_asset_instances_asset_id'), table_name='asset_instances')
    op.drop_table('asset_instances')
    op.drop_index(op.f('ix_activity_log_entity_id'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
